logging:
  config: classpath:logback.xml
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address: ''
      appname: sakura-stock-job-executor
      ip: ''
      logpath: ./logs
      logretentiondays: 30
      port: 9999
